In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
df=pd.read_csv("complete_timeline_data.csv")

In [3]:
df

Sequence_token                                           sequence
0               [1]  CATCATCAATAATATACCTTATAGATGGAATGGTGCCAATATGTAA...
1               [2]  ATCGTGTGGTGATTGGCTGTGGGGTTAACGGCTAAAAGGGGCGGTG...
2               [3]  TGGGGGTGGAGTTTTTTTGCAAGTTGTCGCGGGAAATGTGACGCAT...
3               [4]  TACTTAGTTTTCCCACGGTATTTAACAGGAAATGAGGTAGTTTTGA...
4               [5]  TTTTCGCGCGAAAACTGAATGAGGAAGTGTTTTTCTGAATAATGTG...
5               [6]  TGTTCAGGGCCAGGTAGACTTTGACCCATTACGTGGAGGTTTCGAT...
6               [7]  CGCGTACCGTGTCAAAGTCTTCTGTTTTTACGTAGGTGTCAGCTGA...
7               [8]  GTTTGTGTCAAGAGGCCACTCTTGAGTGCCAGCGAGAAGAGTTTTC...
8               [9]  TAAAAAAATGAGAGATTTGCGATTTCTGCCTCAGGAAATAATCTCT...
9              [10]  GAGCTTGTGGTGCACGCCCTGATGGGAGACGATCCGGAGCCACCTG...
10             [11]  TTCAGGAACTGTATGATTTAGAGGTAGAGGGATCGGAGGATTCTAA...
11             [12]  TACCGATTCTATGCTTTTAGCTGCTAATGAAGGGTTAGAATTAGAT...
12             [13]  CCAGGGGTAATTGTGGAAAGCGGTACAGGTGTAAGAAAATTACCTG...
13             [14]  TGCACTGCTATGAAGACGGGTTTCCTCCGAGTGATGAGGAGGACCA...
14             [15]  TGCAGCGGGTGAGGGAGTGAAGGCTGCCAATGTTGGTTTTCAGTTG...
15             [16]  GGCTGTAAGTCTTGTGAATTTCACAGGAAAAATACTGGAGTAAAGG...
16             [17]  TGAGAACGCACTGCCACTTTATTTACAGTAAGTGTGTTTAAGTTAA...
17             [18]  CACATGTATATTGAGTGTGAGTTTTGTGCTTCTTATTATAGGTCCT...
18             [19]  TCTCCTGATTCTACTACCTCACCTCCTGAGATTCAAGCACCTGTTC...
19             [20]  CTGTGAAGCTTAAGCCTGGGAAACGTCCAGCAGTGGAAAAACTTGA...
20             [21]  ACCTTTGGACTTGAGTACACGGAAACGTCCAAGACAATAAGTGTTC...
21             [22]  CGTCAATATTTGTGTGACAGTGCAATGTAATAAAAATATGTTAACT...
22             [23]  GGGCGGGGACTCAGGTATATAAGTAGAAGCAGACCTGTGTGGTTAG...
23             [24]  TGGAGGTTTGGGCCATTTTGGAAGACCTTAGGAAGACTAGGCAACT...
24             [25]  CTCCGGTTTTTGGAGATTCTGGTTCGCTAGTGAATTAGCTAGGGTA...
25             [26]  AACCAAGAATTTGAAAAGTTGTTGGTAGATTGCCCAGGACTTTTTG...
26             [27]  TTCACTTTAAAGAAAAAGTTTTATCAGTTTTAGACTTTTCAACCCC...
27             [28]  TTTTCTTACTTTTATATTAGATAAATGGATCCCGCAGACTCATTTC...
28             [29]  ATAGCCACAGCATTGTGGAGAACATGGAAGGTTCGCAAGATGAGGA...
29             [30]  AGCCTTTGGGTGTAGCGGGAATCCTGAGGCATCCACCGGTCATGCC...
...             ...                                                ...
2700          [361]  ATGACCAGTTGCTGTAGTTGTCTCAAGGGCTGTTGTTCTTGTGGAT...
2701          [362]  ACTCTGAGCCAGTGCTCAAAGGAGTCAAATTACATTACACATAAAC...
2702          [363]  ATCTTCACAATTGGAACTGTAACTTTGAAGCAAGGTGAAATCAAGG...
2703          [364]  GCGCTACTGCAACGATACCGATACAAGCCTCACTCCCTTTCGGATG...
2704          [365]  TGCTGTTTTTCAGAGCGCTTCCAAAATCATAACCCTCAAAAAGAGA...
2705          [366]  GTTCACTTTGTTTGCAACTTGCTGTTGTTGTTTGTAACAGTTTACT...
2706          [367]  GCCTTGAAGCCCCTTTTCTCTATCTTTATGCTTTAGTCTACTTCTT...
2707          [368]  AATAATGAGGCTTTGGCTTTGCTGGAAATGCCGTTCCAAAAACCCA...
2708          [369]  CTTTGCTGGCATACTAATTGTTACGACTATTGTATACCTTACAATA...
2709          [370]  CTTCAGGTGATGGCACAACAAGTCCTATTTCTGAACATGACTACCA...
2710          [371]  GGAATCTGGAGTAAAAGACTGTGTTGTATTACACAGTTACTTCACT...
2711          [372]  ACTCAATTGAGTACAGACACTGGTGTTGAACATGTTACCTTCTTCA...
2712          [373]  CTGAAGAACATGTCCAAATTCACACAATCGACGGTTCATCCGGAGT...
2713          [374]  TTATGATGAACCGACGACGACTACTAGCGTGCCTTTGTAAGCACAA...
2714          [375]  TCATTCGTTTCGGAAGAGACAGGTACGTTAATAGTTAATAGCGTAC...
2715          [376]  TCTTGCTAGTTACACTAGCCATCCTTACTGCGCTTCGATTGTGTGC...
2716          [377]  GAGTCTTGTAAAACCTTCTTTTTACGTTTACTCTCGTGTTAAAAAT...
2717          [378]  CTTCTGGTCTAAACGAACTAAATATTATATTAGTTTTTCTGTTTGG...
2718          [379]  TTCCAACGGTACTATTACCGTTGAAGAGCTTAAAAAGCTCCTTGAA...
2719          [380]  CTATTCCTTACATGGATTTGTCTTCTACAATTTGCCTATGCCAACA...
2720          [381]  AGTTAATTTTCCTCTGGCTGTTATGGCCAGTAACTTTAGCTTGTTT...
2721          [382]  AAATTGGATCACCGGTGGAATTGCTATCGCAATGGCTTGTCTTGTA...
2722          [383]  ATTGCTTCTTTCAGACTGTTTGCGCGTACGCGTTCCATGTGGTCAT...
2723          [384]  TCAACGTGCCACTCCATGGCACTATTCTGACCAGACCGCTTCTAGA...
2724          [385]  GATCCTTC

In [4]:
df=df.dropna()

In [5]:
df

Sequence_token                                           sequence
0               [1]  CATCATCAATAATATACCTTATAGATGGAATGGTGCCAATATGTAA...
1               [2]  ATCGTGTGGTGATTGGCTGTGGGGTTAACGGCTAAAAGGGGCGGTG...
2               [3]  TGGGGGTGGAGTTTTTTTGCAAGTTGTCGCGGGAAATGTGACGCAT...
3               [4]  TACTTAGTTTTCCCACGGTATTTAACAGGAAATGAGGTAGTTTTGA...
4               [5]  TTTTCGCGCGAAAACTGAATGAGGAAGTGTTTTTCTGAATAATGTG...
5               [6]  TGTTCAGGGCCAGGTAGACTTTGACCCATTACGTGGAGGTTTCGAT...
6               [7]  CGCGTACCGTGTCAAAGTCTTCTGTTTTTACGTAGGTGTCAGCTGA...
7               [8]  GTTTGTGTCAAGAGGCCACTCTTGAGTGCCAGCGAGAAGAGTTTTC...
8               [9]  TAAAAAAATGAGAGATTTGCGATTTCTGCCTCAGGAAATAATCTCT...
9              [10]  GAGCTTGTGGTGCACGCCCTGATGGGAGACGATCCGGAGCCACCTG...
10             [11]  TTCAGGAACTGTATGATTTAGAGGTAGAGGGATCGGAGGATTCTAA...
11             [12]  TACCGATTCTATGCTTTTAGCTGCTAATGAAGGGTTAGAATTAGAT...
12             [13]  CCAGGGGTAATTGTGGAAAGCGGTACAGGTGTAAGAAAATTACCTG...
13             [14]  TGCACTGCTATGAAGACGGGTTTCCTCCGAGTGATGAGGAGGACCA...
14             [15]  TGCAGCGGGTGAGGGAGTGAAGGCTGCCAATGTTGGTTTTCAGTTG...
15             [16]  GGCTGTAAGTCTTGTGAATTTCACAGGAAAAATACTGGAGTAAAGG...
16             [17]  TGAGAACGCACTGCCACTTTATTTACAGTAAGTGTGTTTAAGTTAA...
17             [18]  CACATGTATATTGAGTGTGAGTTTTGTGCTTCTTATTATAGGTCCT...
18             [19]  TCTCCTGATTCTACTACCTCACCTCCTGAGATTCAAGCACCTGTTC...
19             [20]  CTGTGAAGCTTAAGCCTGGGAAACGTCCAGCAGTGGAAAAACTTGA...
20             [21]  ACCTTTGGACTTGAGTACACGGAAACGTCCAAGACAATAAGTGTTC...
21             [22]  CGTCAATATTTGTGTGACAGTGCAATGTAATAAAAATATGTTAACT...
22             [23]  GGGCGGGGACTCAGGTATATAAGTAGAAGCAGACCTGTGTGGTTAG...
23             [24]  TGGAGGTTTGGGCCATTTTGGAAGACCTTAGGAAGACTAGGCAACT...
24             [25]  CTCCGGTTTTTGGAGATTCTGGTTCGCTAGTGAATTAGCTAGGGTA...
25             [26]  AACCAAGAATTTGAAAAGTTGTTGGTAGATTGCCCAGGACTTTTTG...
26             [27]  TTCACTTTAAAGAAAAAGTTTTATCAGTTTTAGACTTTTCAACCCC...
27             [28]  TTTTCTTACTTTTATATTAGATAAATGGATCCCGCAGACTCATTTC...
28             [29]  ATAGCCACAGCATTGTGGAGAACATGGAAGGTTCGCAAGATGAGGA...
29             [30]  AGCCTTTGGGTGTAGCGGGAATCCTGAGGCATCCACCGGTCATGCC...
...             ...                                                ...
2700          [361]  ATGACCAGTTGCTGTAGTTGTCTCAAGGGCTGTTGTTCTTGTGGAT...
2701          [362]  ACTCTGAGCCAGTGCTCAAAGGAGTCAAATTACATTACACATAAAC...
2702          [363]  ATCTTCACAATTGGAACTGTAACTTTGAAGCAAGGTGAAATCAAGG...
2703          [364]  GCGCTACTGCAACGATACCGATACAAGCCTCACTCCCTTTCGGATG...
2704          [365]  TGCTGTTTTTCAGAGCGCTTCCAAAATCATAACCCTCAAAAAGAGA...
2705          [366]  GTTCACTTTGTTTGCAACTTGCTGTTGTTGTTTGTAACAGTTTACT...
2706          [367]  GCCTTGAAGCCCCTTTTCTCTATCTTTATGCTTTAGTCTACTTCTT...
2707          [368]  AATAATGAGGCTTTGGCTTTGCTGGAAATGCCGTTCCAAAAACCCA...
2708          [369]  CTTTGCTGGCATACTAATTGTTACGACTATTGTATACCTTACAATA...
2709          [370]  CTTCAGGTGATGGCACAACAAGTCCTATTTCTGAACATGACTACCA...
2710          [371]  GGAATCTGGAGTAAAAGACTGTGTTGTATTACACAGTTACTTCACT...
2711          [372]  ACTCAATTGAGTACAGACACTGGTGTTGAACATGTTACCTTCTTCA...
2712          [373]  CTGAAGAACATGTCCAAATTCACACAATCGACGGTTCATCCGGAGT...
2713          [374]  TTATGATGAACCGACGACGACTACTAGCGTGCCTTTGTAAGCACAA...
2714          [375]  TCATTCGTTTCGGAAGAGACAGGTACGTTAATAGTTAATAGCGTAC...
2715          [376]  TCTTGCTAGTTACACTAGCCATCCTTACTGCGCTTCGATTGTGTGC...
2716          [377]  GAGTCTTGTAAAACCTTCTTTTTACGTTTACTCTCGTGTTAAAAAT...
2717          [378]  CTTCTGGTCTAAACGAACTAAATATTATATTAGTTTTTCTGTTTGG...
2718          [379]  TTCCAACGGTACTATTACCGTTGAAGAGCTTAAAAAGCTCCTTGAA...
2719          [380]  CTATTCCTTACATGGATTTGTCTTCTACAATTTGCCTATGCCAACA...
2720          [381]  AGTTAATTTTCCTCTGGCTGTTATGGCCAGTAACTTTAGCTTGTTT...
2721          [382]  AAATTGGATCACCGGTGGAATTGCTATCGCAATGGCTTGTCTTGTA...
2722          [383]  ATTGCTTCTTTCAGACTGTTTGCGCGTACGCGTTCCATGTGGTCAT...
2723          [384]  TCAACGTGCCACTCCATGGCACTATTCTGACCAGACCGCTTCTAGA...
2724          [385]  GATCCTTC

In [6]:
abstracts=df['sequence']

In [7]:
(abstracts[1][:426])

'ATCGTGTGGTGATTGGCTGTGGGGTTAACGGCTAAAAGGGGCGGTGCGACCGTGGGAAAATGACGTTTTG\n'

In [8]:
tokenizer=tf.keras.preprocessing.text.Tokenizer(num_words=None,filters='\n',lower=False,char_level=True)

In [9]:
tokenizer.fit_on_texts(abstracts)

In [10]:
sequences=tokenizer.texts_to_sequences(abstracts)

In [11]:
sequences[10][:15]

[1, 1, 4, 2, 3, 3, 2, 2, 4, 1, 3, 1, 2, 1, 3]

In [12]:
df['character_token']=sequences

In [13]:
sequences=np.array(sequences)

In [14]:
sequences.shape

(2730, 71)

In [15]:
idx_word=tokenizer.index_word
' '.join(idx_word[w] for w in sequences[100][:40])

'C G C G A T C C T T C C A G T A C T C T T C T A G C G G A A A C C C G T C T T T'

In [16]:
features=[]
labels=[]
training_length=20
for seq in sequences:
    for i in range(training_length,len(seq)):
        extract=seq[i-training_length:i+1]
        features.append(extract[:-1])
        labels.append(extract[-1])

In [17]:
features

[array([4, 2, 1, 4, 2, 1, 4, 2, 2, 1, 2, 2, 1, 2, 1, 2, 4, 4, 1, 1]),
 array([2, 1, 4, 2, 1, 4, 2, 2, 1, 2, 2, 1, 2, 1, 2, 4, 4, 1, 1, 2]),
 array([1, 4, 2, 1, 4, 2, 2, 1, 2, 2, 1, 2, 1, 2, 4, 4, 1, 1, 2, 1]),
 array([4, 2, 1, 4, 2, 2, 1, 2, 2, 1, 2, 1, 2, 4, 4, 1, 1, 2, 1, 2]),
 array([2, 1, 4, 2, 2, 1, 2, 2, 1, 2, 1, 2, 4, 4, 1, 1, 2, 1, 2, 3]),
 array([1, 4, 2, 2, 1, 2, 2, 1, 2, 1, 2, 4, 4, 1, 1, 2, 1, 2, 3, 2]),
 array([4, 2, 2, 1, 2, 2, 1, 2, 1, 2, 4, 4, 1, 1, 2, 1, 2, 3, 2, 1]),
 array([2, 2, 1, 2, 2, 1, 2, 1, 2, 4, 4, 1, 1, 2, 1, 2, 3, 2, 1, 3]),
 array([2, 1, 2, 2, 1, 2, 1, 2, 4, 4, 1, 1, 2, 1, 2, 3, 2, 1, 3, 3]),
 array([1, 2, 2, 1, 2, 1, 2, 4, 4, 1, 1, 2, 1, 2, 3, 2, 1, 3, 3, 2]),
 array([2, 2, 1, 2, 1, 2, 4, 4, 1, 1, 2, 1, 2, 3, 2, 1, 3, 3, 2, 2]),
 array([2, 1, 2, 1, 2, 4, 4, 1, 1, 2, 1, 2, 3, 2, 1, 3, 3, 2, 2, 1]),
 array([1, 2, 1, 2, 4, 4, 1, 1, 2, 1, 2, 3, 2, 1, 3, 3, 2, 2, 1, 3]),
 array([2, 1, 2, 4, 4, 1, 1, 2, 1, 2, 3, 2, 1, 3, 3, 2, 2, 1, 3, 3]),
 array([1, 2, 4, 4, 

In [18]:
#features=np.array(features)

In [19]:
num_words=len(idx_word)+1
num_words

8

In [20]:
label_array=np.zeros((len(features),num_words),dtype=np.int8)

In [21]:
for example_index,word_index in enumerate(labels):
    label_array[example_index,word_index]=1
label_array.shape

(139230, 8)

In [22]:
label_array

array([[0, 0, 1, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 1, 0, 0]], dtype=int8)

In [23]:
idx_word[np.argmax(label_array)]

'A'

In [24]:
sequences.shape

(2730, 71)

In [25]:
from sklearn.model_selection import train_test_split

In [26]:
sequences=sequences.reshape(7,390,71)

In [27]:
x_train,x_test=train_test_split(sequences,test_size=1/7,shuffle=False)

In [28]:
x_train,x_valid=train_test_split(x_train,test_size=1/6,shuffle=False)

In [29]:
x_valid.shape

(1, 390, 71)

In [30]:
x_train[0].shape

(390, 71)

In [31]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Dropout

In [32]:
model=Sequential()

In [33]:
#recurrent layer
model.add(LSTM(64,input_shape=(390,71),activation='relu',return_sequences=False))

Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor


In [34]:
model.add(Dropout(0.3))

In [35]:
#fully connected layer
model.add(Dense(16,activation='relu'))

In [36]:
#dropout for regularization
model.add(Dropout(0.5))

In [37]:
#output layer
model.add(Dense(num_words,activation='softmax'))

In [38]:
opt=tf.keras.optimizers.Adam(lr=1e-3 ,decay=1e-5)

In [39]:
#compile the model
model.compile(optimizer=opt,loss='categorical_crossentropy',metrics=['accuracy'])

In [109]:
#from tensorflow.keras.callbacks import EarlyStopping,ModelCheckpoint

In [110]:
#callbacks=[EarlyStopping(monitor='val_loss',patience=5),
          #ModelCheckpoint('../models/model.h5')]

In [41]:
history=model.fit(x_train,
                  epochs=5,
                  validation_data=x_valid
                 )

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()